name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: false
          persist-credentials: false

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.21.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint --unstable

      - name: Test
        # remove --no-check after fix.
        run: deno test --allow-net --allow-read --no-check --unstable
